"""
ORM model package: re-exports `Base`, core tenant/RBAC entities from `domain`, and Pulse CMMS tables from `pulse_models`.
Import concrete classes from here in services and routers for a stable public shape.
"""

from app.models.automation_engine import (
    AutomationEvent,
    AutomationFeatureConfig,
    AutomationLog,
    AutomationNotification,
    AutomationStateTracking,
)
from app.models.device_hub import AutomationBleDevice, AutomationGateway, AutomationUnknownDevice
from app.models.base import Base
from app.models.domain import (
    AuditLog,
    Company,
    CompanyFeature,
    ComplianceCategory,
    ComplianceRecord,
    ComplianceRecordStatus,
    ComplianceRule,
    DomainEventRow,
    Invite,
    InventoryItem,
    Invoice,
    InvoiceStatus,
    Job,
    JobInventoryLink,
    JobToolLink,
    MaintenanceLog,
    MaintenanceSchedule,
    NotificationRule,
    PaymentMethod,
    PaymentMethodKind,
    PaymentRail,
    RolePermission,
    SystemLog,
    SystemSecureToken,
    Tool,
    User,
    Zone,
)
from app.models.pulse_models import (
    PulseBeaconEquipment,
    PulseProject,
    PulseProjectAutomationRule,
    PulseProjectTask,
    PulseProximityEventLog,
    PulseUserPerformanceSnapshot,
    PulseScheduleShift,
    PulseTaskDependency,
    PulseWorkRequest,
    PulseWorkerProfile,
)

__all__ = [
    "AutomationEvent",
    "AutomationFeatureConfig",
    "AutomationNotification",
    "AutomationStateTracking",
    "AutomationLog",
    "AutomationBleDevice",
    "AutomationGateway",
    "AutomationUnknownDevice",
    "Base",
    "AuditLog",
    "Company",
    "CompanyFeature",
    "Invite",
    "User",
    "Zone",
    "Tool",
    "DomainEventRow",
    "InventoryItem",
    "Job",
    "JobToolLink",
    "JobInventoryLink",
    "MaintenanceSchedule",
    "MaintenanceLog",
    "NotificationRule",
    "ComplianceRule",
    "ComplianceRecord",
    "ComplianceRecordStatus",
    "ComplianceCategory",
    "PaymentMethod",
    "PaymentMethodKind",
    "PaymentRail",
    "Invoice",
    "InvoiceStatus",
    "RolePermission",
    "SystemLog",
    "SystemSecureToken",
    "PulseWorkRequest",
    "PulseWorkerProfile",
    "PulseProject",
    "PulseProjectAutomationRule",
    "PulseProjectTask",
    "PulseProximityEventLog",
    "PulseUserPerformanceSnapshot",
    "PulseScheduleShift",
    "PulseTaskDependency",
    "PulseBeaconEquipment",
]
