"""
ORM model package: re-exports `Base`, core tenant/RBAC entities from `domain`, and Pulse CMMS tables from `pulse_models`.
Import concrete classes from here in services and routers for a stable public shape.
"""

from app.models.automation_engine import (
    AutomationEvent,
    AutomationFeatureConfig,
    AutomationLog,
    AutomationNotification,
    AutomationStateTracking,
)
from app.models.device_hub import AutomationBleDevice, AutomationGateway, AutomationUnknownDevice
from app.models.base import Base
from app.models.blueprint_models import Blueprint, BlueprintElement
from app.models.facility_map_models import FacilityMap
from app.models.infrastructure_map_models import InfraAsset, InfraAttribute, InfraConnection
from app.models.monitoring_models import (
    AlertSeverity,
    AlertStatus,
    MonitoredSystem,
    MonitoringAlert,
    MonitoringFacility,
    MonitoringZone,
    Sensor,
    SensorReading,
    SensorThreshold,
)
from app.models.domain import (
    AuditLog,
    Company,
    CompanyFeature,
    ComplianceCategory,
    ComplianceRecord,
    ComplianceRecordStatus,
    ComplianceRule,
    DomainEventRow,
    EquipmentPart,
    FacilityEquipment,
    FacilityEquipmentStatus,
    Invite,
    InventoryItem,
    InventoryVendor,
    Job,
    JobInventoryLink,
    JobToolLink,
    MaintenanceLog,
    MaintenanceSchedule,
    TenantNotificationRule,
    RolePermission,
    SystemLog,
    SystemSecureToken,
    Tool,
    User,
    UserAccountStatus,
    Zone,
)
from app.models.pm_models import (
    PmFrequencyType,
    PmTask,
    PmTaskChecklistItem,
    PmTaskPart,
    PulseWorkRequestChecklistItem,
    PulseWorkRequestPartLine,
)
from app.models.pm_coord_models import (
    PmCoordProject,
    PmCoordResourceKind,
    PmCoordRisk,
    PmCoordRiskImpact,
    PmCoordTask,
    PmCoordTaskDependency,
    PmCoordTaskResource,
    PmCoordTaskStatus,
)
from app.models.project_summary_models import ProjectSummary, ProjectSummaryStatus
from app.models.pulse_models import (
    PulseBeaconEquipment,
    PulsePreventativeRule,
    PulseProcedure,
    PulseProject,
    PulseProjectAutomationRule,
    PulseProjectTask,
    PulseProximityEventLog,
    PulseUserPerformanceSnapshot,
    PulseScheduleShift,
    PulseTaskDependency,
    PulseWorkOrderSource,
    PulseWorkOrderType,
    PulseWorkRequest,
    PulseWorkerProfile,
)
from app.models.gamification_models import BadgeDefinition, Review, Task, TaskEvent, UserBadge, UserStats, XpLedger

__all__ = [
    "AlertSeverity",
    "AlertStatus",
    "MonitoredSystem",
    "MonitoringAlert",
    "MonitoringFacility",
    "MonitoringZone",
    "Sensor",
    "SensorReading",
    "SensorThreshold",
    "AutomationEvent",
    "AutomationFeatureConfig",
    "AutomationNotification",
    "AutomationStateTracking",
    "AutomationLog",
    "AutomationBleDevice",
    "AutomationGateway",
    "AutomationUnknownDevice",
    "Base",
    "Blueprint",
    "BlueprintElement",
    "FacilityMap",
    "InfraAsset",
    "InfraAttribute",
    "InfraConnection",
    "AuditLog",
    "Company",
    "CompanyFeature",
    "Invite",
    "User",
    "UserAccountStatus",
    "Zone",
    "Tool",
    "DomainEventRow",
    "EquipmentPart",
    "FacilityEquipment",
    "FacilityEquipmentStatus",
    "InventoryItem",
    "InventoryVendor",
    "Job",
    "JobToolLink",
    "JobInventoryLink",
    "MaintenanceSchedule",
    "MaintenanceLog",
    "TenantNotificationRule",
    "ComplianceRule",
    "ComplianceRecord",
    "ComplianceRecordStatus",
    "ComplianceCategory",
    "RolePermission",
    "SystemLog",
    "SystemSecureToken",
    "PmFrequencyType",
    "PmTask",
    "PmTaskChecklistItem",
    "PmTaskPart",
    "PmCoordProject",
    "PmCoordResourceKind",
    "PmCoordRisk",
    "PmCoordRiskImpact",
    "PmCoordTask",
    "PmCoordTaskDependency",
    "PmCoordTaskResource",
    "PmCoordTaskStatus",
    "ProjectSummary",
    "ProjectSummaryStatus",
    "PulseWorkRequestChecklistItem",
    "PulseWorkRequestPartLine",
    "PulsePreventativeRule",
    "PulseProcedure",
    "PulseWorkOrderSource",
    "PulseWorkOrderType",
    "PulseWorkRequest",
    "PulseWorkerProfile",
    "PulseProject",
    "PulseProjectAutomationRule",
    "PulseProjectTask",
    "PulseProximityEventLog",
    "PulseUserPerformanceSnapshot",
    "PulseScheduleShift",
    "PulseTaskDependency",
    "PulseBeaconEquipment",
    "Task",
    "UserStats",
    "TaskEvent",
    "Review",
    "XpLedger",
    "BadgeDefinition",
    "UserBadge",
]
