"""
Write ``backend/alembic/MIGRATION_HEALTH_REPORT.md`` (summary of migration risk surface).

Run from ``backend``:
  python scripts/generate_migration_health_report.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSIONS = ROOT / "alembic" / "versions"
OUT = ROOT / "alembic" / "MIGRATION_HEALTH_REPORT.md"

EXEC_RE = re.compile(r"\bop\.execute\s*\(")
CONN_EXEC_RE = re.compile(r"\bconn\.execute\s*\(")
ALTER_RE = re.compile(r"(?i)\bALTER\s+TABLE\b")
CREATE_INDEX_RE = re.compile(r"(?i)\bCREATE\s+(UNIQUE\s+)?INDEX\b")
ON_CONFLICT_RE = re.compile(r"(?i)ON\s+CONFLICT\b")
IF_NOT_EXISTS_RE = re.compile(r"(?i)IF\s+NOT\s+EXISTS\b")
IF_EXISTS_RE = re.compile(r"(?i)IF\s+EXISTS\b")


def _count(path: Path, pattern: re.Pattern[str]) -> int:
    return len(pattern.findall(path.read_text(encoding="utf-8")))


def _op_execute_lines(path: Path) -> list[int]:
    out: list[int] = []
    for i, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if "op.execute" in line and not line.strip().startswith("#"):
            out.append(i)
    return out


def _safe_alter_files() -> list[str]:
    out: list[str] = []
    for p in sorted(VERSIONS.glob("*.py")):
        if "ah.safe_alter_column" in p.read_text(encoding="utf-8"):
            out.append(p.name)
    return sorted(out)


def main() -> None:
    rows: list[tuple[str, int, int, list[int]]] = []
    risky: list[str] = []
    for p in sorted(VERSIONS.glob("*.py")):
        if p.name == "0001_initial_schema.py":
            continue
        body = p.read_text(encoding="utf-8")
        n_op = _count(p, EXEC_RE)
        n_conn = _count(p, CONN_EXEC_RE)
        if n_op == 0 and n_conn == 0:
            continue
        op_lines = _op_execute_lines(p) if n_op else []
        rows.append((p.name, n_op, n_conn, op_lines))
        if n_op and not ON_CONFLICT_RE.search(body) and not IF_NOT_EXISTS_RE.search(body):
            if (ALTER_RE.search(body) or CREATE_INDEX_RE.search(body)) and not IF_EXISTS_RE.search(body):
                risky.append(p.name)

    lines: list[str] = [
        "# Migration health report",
        "",
        "Auto-generated by `python scripts/generate_migration_health_report.py`.",
        "",
        "## 1. Revisions using `op.execute` / `conn.execute`",
        "",
        "| revision | op.execute | conn.execute | op.execute lines (sample) |",
        "|----------|------------|--------------|-----------------------------|",
    ]
    for name, n_op, n_conn, op_lines in rows:
        sample = ", ".join(str(x) for x in op_lines[:12]) + (" …" if len(op_lines) > 12 else "")
        lines.append(f"| `{name}` | {n_op} | {n_conn} | {sample} |")

    lines.extend(
        [
            "",
            "## 2. Exempt from structural `safe_*` lint (`migration_lint_lib`)",
            "",
            "- `0001_initial_schema.py` — `Base.metadata.create_all` / `drop_all` baseline.",
            "",
            "## 3. `ah.safe_alter_column` usage (review for row-level / cast risks)",
            "",
        ]
    )
    for name in _safe_alter_files():
        lines.append(f"- `{name}`")

    lines.extend(
        [
            "",
            "## 4. Heuristic: `op.execute` + ALTER/CREATE INDEX without obvious idempotence guards",
            "",
            "Manual review (false positives possible):",
            "",
        ]
    )
    for name in sorted(set(risky)):
        lines.append(f"- `{name}`")

    lines.extend(
        [
            "",
            "## 5. Operational notes",
            "",
            "- Prefer `ah.logged_execute(op, sql, operation=..., revision=revision)` for non-trivial SQL.",
            "- `safe_alter_column` checks column existence, not whether NOT NULL is satisfiable.",
            "- Data migrations should use `ON CONFLICT`, `IF EXISTS`, or keyed `WHERE` guards when possible.",
            "",
        ]
    )

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
