import { expandInclusiveDateRange, parseLocalDate } from "@/lib/schedule/calendar";
import type { RecurringShiftRule, Shift, ShiftTypeKey, TimeOffBlock, Worker } from "@/lib/schedule/types";
import { usesStructuredRecurringSchedule } from "@/lib/schedule/worker-scheduling-model";

const AUTO_REC_PREFIX = "auto-rec-";
const PTO_BLOCK_PREFIX = "pto-block-";

export function isEphemeralScheduleShiftId(id: string): boolean {
  return id.startsWith(AUTO_REC_PREFIX) || id.startsWith(PTO_BLOCK_PREFIX);
}

const WEEKDAY_KEYS = [
  "sunday",
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
] as const;

export function weekdayKeyFromIso(iso: string): string {
  const d = parseLocalDate(iso);
  return WEEKDAY_KEYS[d.getDay()];
}

export function normalizeWeekdayKey(raw: string): string {
  return String(raw).trim().toLowerCase();
}

export function inferShiftTypeFromStart(start: string): ShiftTypeKey {
  const [sh] = start.split(":").map(Number);
  if (!Number.isFinite(sh)) return "day";
  if (sh >= 18) return "night";
  if (sh >= 14) return "afternoon";
  return "day";
}

/** Standard placement windows when assigning from the roster (matches typical roster presets). */
export function defaultWindowForShiftBand(key: ShiftTypeKey): { start: string; end: string } {
  if (key === "night") return { start: "22:00", end: "06:00" };
  if (key === "afternoon") return { start: "14:00", end: "22:00" };
  return { start: "07:00", end: "15:00" };
}

export function approvedTimeOffKind(
  workerId: string,
  date: string,
  blocks: TimeOffBlock[],
): "vacation" | "sick" | null {
  for (const b of blocks) {
    if (b.workerId !== workerId || b.status !== "approved") continue;
    if (date >= b.startDate && date <= b.endDate) {
      return b.kind === "sick" ? "sick" : "vacation";
    }
  }
  return null;
}

function hasWorkforceWorkShift(base: Shift[], workerId: string, date: string): boolean {
  return base.some(
    (s) =>
      s.workerId === workerId &&
      s.date === date &&
      s.shiftKind !== "project_task" &&
      s.eventType === "work" &&
      !s.autoGenerated,
  );
}

function hasVacationOrSickCoverage(base: Shift[], workerId: string, date: string): boolean {
  return base.some(
    (s) =>
      s.workerId === workerId &&
      s.date === date &&
      (s.eventType === "vacation" || s.eventType === "sick"),
  );
}

/**
 * Strips locally generated rows so a fresh merge can recompute from API + rules.
 */
export function stripEphemeralShifts(shifts: Shift[]): Shift[] {
  return shifts.filter((s) => !isEphemeralScheduleShiftId(s.id));
}

export function mergeEphemeralSchedule(
  baseShifts: Shift[],
  workers: Worker[],
  visibleDates: string[],
  timeOffBlocks: TimeOffBlock[],
  defaultZoneId: string,
): Shift[] {
  const base = stripEphemeralShifts(baseShifts);
  const visible = new Set(visibleDates);
  const recurring = buildRecurringShifts(base, workers, visible, timeOffBlocks, defaultZoneId);
  const markers = buildTimeOffMarkers(base, workers, timeOffBlocks, visible, defaultZoneId);
  return [...base, ...recurring, ...markers];
}

function buildRecurringShifts(
  base: Shift[],
  workers: Worker[],
  visible: Set<string>,
  timeOffBlocks: TimeOffBlock[],
  defaultZoneId: string,
): Shift[] {
  const out: Shift[] = [];
  for (const w of workers) {
    if (!usesStructuredRecurringSchedule(w)) continue;
    const byDow = new Map<string, RecurringShiftRule>();
    for (const r of w.recurringShifts ?? []) {
      const k = normalizeWeekdayKey(String(r.dayOfWeek));
      if (!byDow.has(k)) byDow.set(k, r);
    }
    for (const date of visible) {
      const dow = weekdayKeyFromIso(date);
      const rule = byDow.get(dow);
      if (!rule) continue;
      const off = approvedTimeOffKind(w.id, date, timeOffBlocks);
      if (off) continue;
      if (hasWorkforceWorkShift(base, w.id, date)) continue;
      const id = `${AUTO_REC_PREFIX}${w.id}-${date}`;
      if (out.some((s) => s.id === id)) continue;
      out.push({
        id,
        workerId: w.id,
        date,
        startTime: rule.start,
        endTime: rule.end,
        shiftType: inferShiftTypeFromStart(rule.start),
        eventType: "work",
        role: (rule.role ?? w.role) as Shift["role"],
        zoneId: defaultZoneId,
        shiftKind: "workforce",
        required_certifications: rule.requiredCertifications?.filter(Boolean),
        autoGenerated: true,
      });
    }
  }
  return out;
}

function buildTimeOffMarkers(
  base: Shift[],
  workers: Worker[],
  blocks: TimeOffBlock[],
  visible: Set<string>,
  defaultZoneId: string,
): Shift[] {
  const out: Shift[] = [];
  const workerMap = new Map(workers.map((w) => [w.id, w]));
  for (const b of blocks) {
    if (b.status !== "approved") continue;
    const kind = b.kind === "sick" ? "sick" : "vacation";
    const dates = expandInclusiveDateRange(b.startDate, b.endDate).filter((d) => visible.has(d));
    for (const date of dates) {
      if (hasVacationOrSickCoverage(base, b.workerId, date)) continue;
      if (out.some((s) => s.workerId === b.workerId && s.date === date && (s.eventType === "vacation" || s.eventType === "sick"))) {
        continue;
      }
      const w = workerMap.get(b.workerId);
      out.push({
        id: `${PTO_BLOCK_PREFIX}${b.id}-${date}`,
        workerId: b.workerId,
        date,
        startTime: "08:00",
        endTime: "16:00",
        shiftType: "day",
        eventType: kind === "sick" ? "sick" : "vacation",
        role: w?.role ?? "worker",
        zoneId: defaultZoneId,
        shiftKind: "workforce",
        autoGenerated: true,
      });
    }
  }
  return out;
}
