/** Duty role id (built-ins: worker | supervisor | lead; settings may add more). */
export type ScheduleDutyRole = string;

/** Shift bucket for color / scheduling. */
export type ShiftTypeKey = "day" | "afternoon" | "night";

/** Roster drag: use recurring template vs fixed day/afternoon/night window. */
export type SchedulePlacementBand = "template" | ShiftTypeKey;

/** One row in Schedule settings → Placement panel → “Shift window” dropdown. */
export type PlacementBandOption = {
  band: SchedulePlacementBand;
  label: string;
  enabled?: boolean;
};

export type ShiftEventType = "work" | "training" | "vacation" | "sick";

export type TimeFormat = "12h" | "24h";

export type EmploymentType = "full_time" | "regular_part_time" | "part_time";

/** Lowercase weekday keys (Monday–Sunday). */
export type WeekdayKey =
  | "monday"
  | "tuesday"
  | "wednesday"
  | "thursday"
  | "friday"
  | "saturday"
  | "sunday";

export type DayAvailability = {
  available: boolean;
  start?: string;
  end?: string;
};

export type RecurringShiftRule = {
  dayOfWeek: WeekdayKey | string;
  start: string;
  end: string;
  role?: ScheduleDutyRole;
  /** Certs required for this recurring template (drag highlights + new shifts). */
  requiredCertifications?: string[];
};

/** Structured scheduling constraints (availability layer). Optional; merges with `availability` windows. */
export type WorkerSchedulingConstraints = {
  noNights?: boolean;
  afternoonsOnly?: boolean;
  morningsOnly?: boolean;
};

export interface Worker {
  id: string;
  name: string;
  /** Primary job role for this person (used as default in forms). */
  role: ScheduleDutyRole;
  active: boolean;
  employmentType?: EmploymentType;
  /** Hard / band constraints for operational scheduling (see `availability-layer`). */
  schedulingConstraints?: WorkerSchedulingConstraints;
  /**
   * Per-weekday availability windows. Keys are weekday names (any case); normalized client-side.
   */
  availability?: Partial<Record<string, DayAvailability>>;
  /** Optional certs for conflict hints (built-ins include RO, P1, P2, FA; free-text codes ok). */
  certifications?: string[];
  /** Templates used to auto-fill workforce shifts for visible calendar dates. */
  recurringShifts?: RecurringShiftRule[];
}

/** Approved (or mock) time-off: used only for conflict hints + future scheduling blocks. */
export interface TimeOffBlock {
  id: string;
  workerId: string;
  startDate: string;
  endDate: string;
  status: "approved" | "pending";
  /** Drives override styling and suppresses recurring work shifts. */
  kind?: "vacation" | "sick";
}

/** Active HTML5 drag session for the schedule surface (shift chip vs worker roster). */
export type ScheduleDragSession =
  | { kind: "shift"; shiftId: string; duplicate: boolean }
  | { kind: "worker"; workerId: string };

/** Optional UI hints for future notifications (no backend yet). */
export type ShiftUiFlags = {
  isNew?: boolean;
  isUpdated?: boolean;
};

export type ShiftKind = "workforce" | "project_task";

export type TaskPriority = "low" | "medium" | "high" | "critical";

export interface Shift {
  id: string;
  workerId: string | null;
  /** Local calendar date YYYY-MM-DD */
  date: string;
  /** HH:mm 24h */
  startTime: string;
  endTime: string;
  shiftType: ShiftTypeKey;
  /** Work, training block, or PTO-style entry. */
  eventType: ShiftEventType;
  role: ScheduleDutyRole;
  /** Pulse `zone_id` — always a **schedule facility** (org Settings → Schedule → Facilities), not equipment/blueprint zones. */
  zoneId: string;
  /** Pulse schedule phase 1: optional shift definition link. */
  shiftDefinitionId?: string | null;
  /** Denormalized shift code from definition (e.g. D1, PM2). */
  shiftCode?: string | null;
  /**
   * Operational metadata badges (TRN, PTO, GG, …) — separate from shift identity.
   * Rendered as compact pills; source can be API metadata later.
   */
  operationalBadges?: string[];
  /** When a manager placed shift despite availability, audit trail hook. */
  availabilityOverrideReason?: string | null;
  /** Server-side publish workflow flags (not fully used in UI yet). */
  isDraft?: boolean;
  publishedAt?: string | null;
  /** Pulse API: workforce vs linked project task (calendar line). */
  shiftKind?: ShiftKind;
  projectTaskId?: string;
  projectId?: string;
  projectName?: string;
  /** Primary line on calendar chip when `shiftKind === "project_task"`. */
  taskTitle?: string;
  taskPriority?: TaskPriority;
  /** Optional staffing rules for this shift (conflict UI only; non-blocking). */
  required_certifications?: string[];
  /** When true, assigned worker needs at least one cert from `required_certifications`; otherwise all are required. */
  accepts_any_certification?: boolean;
  requires_supervisor?: boolean;
  minimum_workers?: number;
  uiFlags?: ShiftUiFlags;
  /** Generated locally from recurring templates or time-off markers (not from Pulse API). */
  autoGenerated?: boolean;
}

export interface Zone {
  id: string;
  label: string;
  /** Optional metadata from Pulse zones (e.g. building info). */
  meta?: Record<string, unknown>;
}

export interface ScheduleRoleDefinition {
  id: ScheduleDutyRole;
  label: string;
}

export interface ShiftTypeConfig {
  key: ShiftTypeKey;
  label: string;
  /** Tailwind bg classes (subtle) */
  bg: string;
  border: string;
  text: string;
}

export interface ScheduleSettings {
  workDayStart: string;
  workDayEnd: string;
  shiftDurationPresets: { id: string; label: string; hours: number }[];
  timeFormat: TimeFormat;
  staffing: {
    minWorkersPerShift: number;
    requireSupervisor: boolean;
    maxHoursPerWorkerPerWeek: number;
    /**
     * When false (default), OT risk shows as “No OT risk” and no elevated/moderate levels are shown.
     * Managers may enable to evaluate scheduled work hours vs `maxHoursPerWorkerPerWeek` per Mon–Sun week.
     */
    otRiskMonitoringEnabled?: boolean;
  };
  /** Approximate slots per day for fill % (mock capacity until headcount API exists). */
  requiredShiftsPerDay: number;
  activeWorkerTarget: number;
  /**
   * Workers sidebar — “Shift window” menu: order, labels, and visibility.
   * Omit to use built-in defaults (template + day / afternoon / night presets).
   */
  placementBandOptions?: PlacementBandOption[];
  /**
   * Workers sidebar — “Role when placing”: subset of {@link ScheduleRoleDefinition} IDs in display order.
   * Omit or empty → all roles from the roster definition list.
   */
  placementPanelRoleIds?: string[];
}

export interface ScheduleAlerts {
  /**
   * Legacy field — supervisor coverage is no longer surfaced as an alert (always 0).
   * Prefer {@link roP4BandGapCount} for staffing intelligence.
   */
  daysMissingSupervisor: number;
  /** Shifts with no worker assigned. */
  unassignedShiftCount: number;
  /** Legacy — always 0; supervisor slot alerts removed. */
  openSupervisorSlots: number;
  /**
   * Staffed day / afternoon / night bands in the focused month missing any worker with RO or P4.
   */
  roP4BandGapCount: number;
  /** Coverage rule violations (critical). */
  coverageCritical: number;
  /** Coverage rule violations (warning). */
  coverageWarnings: number;
}

export interface WorkforceSummary {
  activeWorkers: number;
  activeTarget: number;
  /** `None` = no OT risk surfaced (monitoring off or no workers over weekly cap). */
  otRiskLabel: "None" | "Low" | "Moderate" | "Elevated";
  fillPercent: number;
  pendingRequests: number;
}
