/**
 * Master feature registry — single source of truth for tenant product modules.
 *
 * Authorization: registry → tenant contract → `enabled_features` (matrix ∪ overlays) → RBAC.
 * Presentation fields (`navDomain`, `navGroup`, `dashboardScope`, …) are never used for access checks.
 */
import type { DashboardScope } from "@/config/platform/dashboard-scope";
import {
  DASHBOARD_ACCESS_REGISTRY,
  dashboardRbacAnyOf,
  enabledFeatureKeyForDashboard,
} from "@/lib/dashboards/dashboard-permissions";
import type { ModuleCategory } from "@/config/platform/module-categories";
import type { NavDomain } from "@/config/platform/nav-domains";
import type { PlatformIconKey } from "@/config/platform/types";

/** Department blank dashboards appear in the owning workflow domain (Communications, Aquatics, …). */
function navDomainForDepartmentDashboard(ownershipDepartment?: string): NavDomain {
  const slug = (ownershipDepartment ?? "").trim().toLowerCase();
  const map: Record<string, NavDomain> = {
    communications: "Communications",
    aquatics: "Aquatics",
    reception: "Reception",
    fitness: "Fitness",
    racquets: "Racquets",
    admin: "Administration",
  };
  return map[slug] ?? "Dashboards";
}

export type MasterFeatureIcon =
  | PlatformIconKey
  | "activity"
  | "folder-kanban"
  | "list-checks"
  | "sparkles"
  | "user-cog"
  | "users"
  | "map-pin"
  | "radio"
  | "scan-barcode"
  | "settings"
  | "layers";

export type MasterFeatureDef = {
  /** Stable feature id (globally unique). */
  key: string;
  label: string;
  icon: MasterFeatureIcon;
  /** Canonical application route (one module, one route). */
  route: string;
  /** Canonical feature key (`/auth/me` `enabled_features`). */
  feature: string;
  rbacAnyOf: readonly string[];
  navVisible: boolean;
  /** Legacy platform shell: `/{platformDepartmentSlug}/{platformRoute}` → `route`. */
  platformDepartmentSlug?: string;
  platformRoute?: string;
  sortOrder: number;
  /**
   * Sidebar section label (presentation only). Omitted → {@link DEFAULT_MODULE_CATEGORY}.
   * @deprecated Prefer {@link navDomain} + {@link navGroup}.
   */
  moduleCategory?: ModuleCategory;
  /** Workflow-oriented top-level sidebar domain (presentation only). */
  navDomain: NavDomain;
  /** Flyout subsection label within {@link navDomain} (presentation only). */
  navGroup?: string;
  /** Sort order within nav group / domain (presentation only). Falls back to {@link sortOrder}. */
  navOrder?: number;
  /** Optional sidebar/flyout label override (presentation only). */
  navLabelOverride?: string;
  /** Dashboard scope for dashboard surfaces (presentation only). */
  dashboardScope?: DashboardScope;
  /**
   * Department that owns/configures a department-scoped dashboard (presentation only).
   * Example: maintenance dashboards remain owned by maintenance while using shared dashboard infrastructure.
   */
  ownershipDepartment?: string;
  /** When true, row is a navigation alias (same permission feature may appear in multiple domains). */
  navAlias?: boolean;
};

/**
 * Globally unique operational features — one row per product module or navigation alias.
 */
export const MASTER_FEATURES: readonly MasterFeatureDef[] = [
  // —— Dashboards ——
  {
    key: "dashboard",
    label: "Leadership dashboard",
    icon: "layout",
    route: "/overview",
    feature: "dashboard_leadership",
    rbacAnyOf: [...dashboardRbacAnyOf("dashboard.leadership.view")],
    navVisible: true,
    sortOrder: 10,
    navDomain: "Dashboards",
    navGroup: "Shared Dashboards",
    navOrder: 10,
    dashboardScope: "organization",
  },
  {
    key: "dashboard_worker",
    label: "Operations dashboard",
    icon: "layout",
    route: "/worker",
    feature: "dashboard_operations",
    rbacAnyOf: [...dashboardRbacAnyOf("dashboard.operations.view")],
    navVisible: true,
    sortOrder: 11,
    navDomain: "Dashboards",
    navGroup: "My Dashboards",
    navOrder: 15,
    dashboardScope: "personal",
    navAlias: true,
  },
  {
    key: "dashboard_project",
    label: "Project dashboard",
    icon: "folder-kanban",
    route: "/overview/project",
    feature: "dashboard_project",
    rbacAnyOf: [...dashboardRbacAnyOf("dashboard.project.view"), "projects.view"],
    navVisible: true,
    sortOrder: 12,
    navDomain: "Dashboards",
    navGroup: "Project Dashboards",
    navOrder: 20,
    dashboardScope: "project",
    navAlias: true,
  },
  {
    key: "monitoring",
    label: "Monitoring",
    icon: "activity",
    route: "/monitoring",
    feature: "monitoring",
    rbacAnyOf: ["monitoring.view"],
    navVisible: true,
    sortOrder: 20,
    navDomain: "Operations",
    navGroup: "Monitoring",
    navOrder: 25,
    dashboardScope: "shared",
  },
  {
    key: "logs_inspections",
    label: "Logs & Inspections",
    icon: "scroll-text",
    route: "/dashboard/compliance",
    feature: "logs_inspections",
    rbacAnyOf: ["compliance.view"],
    navVisible: true,
    sortOrder: 40,
    navDomain: "Operations",
    navGroup: "Logs & Inspections",
    navOrder: 10,
    dashboardScope: "department",
    ownershipDepartment: "maintenance",
  },
  {
    key: "logs_inspections_dashboard",
    label: "Inspections & Logs",
    icon: "scroll-text",
    route: "/dashboard/compliance",
    feature: "logs_inspections",
    rbacAnyOf: [...dashboardRbacAnyOf("dashboard.inspections.view"), "compliance.view"],
    navVisible: false,
    sortOrder: 41,
    navDomain: "Dashboards",
    navGroup: "Department Dashboards",
    navOrder: 50,
    dashboardScope: "department",
    ownershipDepartment: "maintenance",
    navAlias: true,
  },
  {
    key: "work_requests",
    label: "Work Requests",
    icon: "clipboard",
    route: "/dashboard/maintenance",
    feature: "work_requests",
    rbacAnyOf: ["work_requests.view", "work_requests.edit"],
    navVisible: true,
    sortOrder: 50,
    navDomain: "Operations",
    navGroup: "Work Requests",
    navOrder: 5,
    dashboardScope: "department",
    ownershipDepartment: "maintenance",
  },
  {
    key: "operational_improvements",
    label: "Operational Improvements",
    icon: "sparkles",
    route: "/dashboard/operational-improvements",
    feature: "operational_improvements",
    rbacAnyOf: ["operational_improvements.view", "operational_improvements.manage"],
    navVisible: true,
    sortOrder: 52,
    navDomain: "Operations",
    navGroup: "Continuous Improvement",
    navOrder: 8,
    dashboardScope: "shared",
  },
  ...DASHBOARD_ACCESS_REGISTRY.filter((d) => d.id.startsWith("dashboard_dept_")).map((d) => ({
    key: d.id,
    label: d.label,
    icon: d.icon,
    route: d.route,
    feature: enabledFeatureKeyForDashboard(d),
    rbacAnyOf: [...dashboardRbacAnyOf(d.viewPermission)],
    navVisible: true,
    sortOrder: d.sortOrder,
    navDomain: navDomainForDepartmentDashboard(d.ownershipDepartment),
    navGroup: "Dashboard",
    navOrder: 5,
    dashboardScope: "department" as const,
    ownershipDepartment: d.ownershipDepartment,
    navAlias: true,
  })),

  // —— Planning ——
  {
    key: "planning_workspace",
    label: "Planning",
    icon: "calendar",
    route: "/planning",
    feature: "projects",
    rbacAnyOf: ["projects.view"],
    navVisible: false,
    sortOrder: 99,
    navDomain: "Planning",
    navGroup: "Projects",
    navOrder: 15,
    navAlias: true,
  },
  {
    key: "schedule",
    label: "Schedule",
    icon: "calendar",
    route: "/schedule",
    feature: "schedule",
    rbacAnyOf: ["schedule.view"],
    navVisible: true,
    sortOrder: 100,
    navDomain: "Planning",
    navGroup: "Scheduling",
    navOrder: 10,
  },
  {
    key: "schedule_availability",
    label: "Availability",
    icon: "calendar",
    route: "/schedule/availability",
    feature: "schedule_availability",
    rbacAnyOf: ["schedule.view"],
    navVisible: false,
    sortOrder: 101,
    navDomain: "Planning",
    navGroup: "Scheduling",
    navOrder: 20,
    navAlias: true,
  },
  {
    key: "schedule_coverage",
    label: "Coverage",
    icon: "calendar",
    route: "/schedule/availability-grid",
    feature: "schedule_coverage",
    rbacAnyOf: ["schedule.view"],
    navVisible: false,
    sortOrder: 102,
    navDomain: "Planning",
    navGroup: "Scheduling",
    navOrder: 30,
    navAlias: true,
  },
  {
    key: "schedule_shift_definitions",
    label: "Shift definitions",
    icon: "calendar",
    route: "/schedule/shift-definitions",
    feature: "schedule_shift_definitions",
    rbacAnyOf: ["schedule.view"],
    navVisible: false,
    sortOrder: 103,
    navDomain: "Planning",
    navGroup: "Scheduling",
    navOrder: 40,
    navAlias: true,
  },
  {
    key: "projects",
    label: "Projects",
    icon: "folder-kanban",
    route: "/projects",
    feature: "projects",
    rbacAnyOf: ["projects.view"],
    navVisible: true,
    sortOrder: 110,
    navDomain: "Planning",
    navGroup: "Projects",
    navOrder: 10,
  },
  {
    key: "roadmap",
    label: "Roadmap",
    icon: "calendar",
    route: "/roadmap",
    feature: "projects",
    rbacAnyOf: ["projects.view", "roadmap.view", "roadmap.manage"],
    navVisible: true,
    sortOrder: 109,
    navDomain: "Planning",
    navGroup: "Projects",
    navOrder: 5,
  },
  {
    key: "daily_planner",
    label: "Daily Planner",
    icon: "calendar",
    route: "/planner",
    feature: "daily_planner",
    rbacAnyOf: ["daily_planner.view", "daily_planner.manage"],
    navVisible: true,
    sortOrder: 112,
    navDomain: "My Role",
    navGroup: "Planner",
    navOrder: 1,
  },
  {
    key: "daily_planner_inbox",
    label: "Task Inbox",
    icon: "list-checks",
    route: "/planner/inbox",
    feature: "daily_planner",
    rbacAnyOf: ["daily_planner.view", "daily_planner.manage"],
    navVisible: true,
    sortOrder: 113,
    navDomain: "My Role",
    navGroup: "Planner",
    navOrder: 2,
  },
  {
    key: "daily_planner_routine",
    label: "Daily Routine",
    icon: "settings",
    route: "/planner/routine",
    feature: "daily_planner",
    rbacAnyOf: ["daily_planner.view", "daily_planner.manage"],
    navVisible: true,
    sortOrder: 114,
    navDomain: "My Role",
    navGroup: "Planner",
    navOrder: 3,
  },
  {
    key: "daily_planner_analytics",
    label: "Planner Analytics",
    icon: "activity",
    route: "/planner/analytics",
    feature: "daily_planner",
    rbacAnyOf: ["daily_planner.view", "daily_planner.manage"],
    navVisible: true,
    sortOrder: 115,
    navDomain: "My Role",
    navGroup: "Planner",
    navOrder: 4,
  },
  {
    key: "ops_command_center",
    label: "Command Center",
    icon: "building",
    route: "/recreation",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: false,
    sortOrder: 116,
    navDomain: "My Role",
    navGroup: "Command",
    navOrder: 1,
  },
  {
    key: "ops_me",
    label: "My Profile",
    icon: "user-cog",
    route: "/recreation/me",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 117,
    navDomain: "My Role",
    navGroup: "Command",
    navOrder: 2,
  },
  {
    key: "ops_checklists",
    label: "Checklists",
    icon: "list-checks",
    route: "/recreation/checklists",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 118,
    navDomain: "My Role",
    navGroup: "Command",
    navOrder: 3,
  },
  {
    key: "ops_knowledge_gaps",
    label: "Knowledge Gaps",
    icon: "activity",
    route: "/recreation/knowledge-gaps",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 119,
    navDomain: "My Role",
    navGroup: "Command",
    navOrder: 4,
  },
  {
    key: "ops_org_chart",
    label: "Org Chart",
    icon: "users",
    route: "/recreation/org-chart",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 119,
    navDomain: "My Role",
    navGroup: "Organization",
    navOrder: 5,
  },
  {
    key: "ops_team_development",
    label: "Team Development",
    icon: "sparkles",
    route: "/recreation/team-development",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 119,
    navDomain: "My Role",
    navGroup: "Organization",
    navOrder: 6,
  },
  {
    key: "ops_copilot",
    label: "Ops Copilot",
    icon: "message-square",
    route: "/recreation/copilot",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 119,
    navDomain: "My Role",
    navGroup: "Intelligence",
    navOrder: 7,
  },
  {
    key: "ops_attention",
    label: "Operational Attention",
    icon: "activity",
    route: "/recreation/attention",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: false,
    sortOrder: 119,
    navDomain: "My Role",
    navGroup: "Intelligence",
    navOrder: 7,
  },
  {
    key: "ops_emergency",
    label: "Emergency Response",
    icon: "radio",
    route: "/recreation/emergency",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 119,
    navDomain: "My Role",
    navGroup: "Intelligence",
    navOrder: 8,
  },
  {
    key: "ops_planning_hub",
    label: "Planning Hub",
    icon: "folder-kanban",
    route: "/recreation/planning",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: false,
    sortOrder: 119,
    navDomain: "My Role",
    navGroup: "Planning",
    navOrder: 9,
  },
  {
    key: "ops_reports",
    label: "Reports & Export",
    icon: "file-text",
    route: "/recreation/reports",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 119,
    navDomain: "My Role",
    navGroup: "Reporting",
    navOrder: 10,
  },
  {
    key: "ops_knowledge",
    label: "Knowledge Base",
    icon: "book-open",
    route: "/recreation/knowledge",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 120,
    navDomain: "My Role",
    navGroup: "Knowledge",
    navOrder: 10,
  },
  {
    key: "ops_meetings",
    label: "Meetings",
    icon: "users",
    route: "/recreation/meetings",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 121,
    navDomain: "My Role",
    navGroup: "Coordination",
    navOrder: 20,
  },
  {
    key: "ops_people",
    label: "People",
    icon: "users",
    route: "/recreation/people",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 122,
    navDomain: "My Role",
    navGroup: "Directory",
    navOrder: 30,
  },
  {
    key: "ops_contractors",
    label: "Contractors",
    icon: "wrench",
    route: "/recreation/contractors",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 123,
    navDomain: "My Role",
    navGroup: "Directory",
    navOrder: 40,
  },
  {
    key: "ops_regulations",
    label: "Regulations",
    icon: "scroll-text",
    route: "/recreation/regulations",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 124,
    navDomain: "My Role",
    navGroup: "Compliance",
    navOrder: 50,
  },
  {
    key: "ops_facilities",
    label: "Facilities",
    icon: "building",
    route: "/recreation/facilities",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 125,
    navDomain: "My Role",
    navGroup: "Facilities",
    navOrder: 60,
  },
  {
    key: "ops_quick_notes",
    label: "Quick Notes",
    icon: "clipboard",
    route: "/recreation/quick-notes",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 126,
    navDomain: "My Role",
    navGroup: "Capture",
    navOrder: 70,
  },
  {
    key: "ops_contacts",
    label: "Contacts",
    icon: "megaphone",
    route: "/recreation/contacts",
    feature: "recreation_ops",
    rbacAnyOf: ["recreation_ops.view", "recreation_ops.manage"],
    navVisible: true,
    sortOrder: 127,
    navDomain: "My Role",
    navGroup: "Directory",
    navOrder: 80,
  },
  {
    key: "pm_workspace",
    label: "PM workspace",
    icon: "folder-kanban",
    route: "/dashboard/pm-workspace",
    feature: "pm_workspace",
    rbacAnyOf: ["projects.pm.view"],
    navVisible: false,
    sortOrder: 111,
    navDomain: "Planning",
    navGroup: "Projects",
    navOrder: 20,
    navAlias: true,
  },
  {
    key: "pm_planning",
    label: "PM planning",
    icon: "folder-kanban",
    route: "/pm/planning",
    feature: "pm_planning",
    rbacAnyOf: ["projects.pm.view"],
    navVisible: false,
    sortOrder: 112,
    navDomain: "Planning",
    navGroup: "Projects",
    navOrder: 30,
    navAlias: true,
  },
  {
    key: "project_management",
    label: "Project Management",
    icon: "folder-kanban",
    route: "/project-management",
    feature: "project_management",
    rbacAnyOf: ["projects.pm.view"],
    navVisible: true,
    sortOrder: 111,
    navDomain: "Planning",
    navGroup: "Projects",
    navOrder: 20,
    navAlias: true,
  },
  {
    key: "comms_campaign_planner",
    label: "Social Planner",
    icon: "calendar",
    route: "/communications/campaign-planner",
    feature: "comms_campaign_planner",
    rbacAnyOf: ["social_planner.view"],
    navVisible: true,
    platformDepartmentSlug: "communications",
    platformRoute: "campaign-planner",
    sortOrder: 120,
    moduleCategory: "Communications",
    navDomain: "Communications",
    navGroup: "Campaigns",
    navOrder: 40,
  },

  // —— Operations ——
  {
    key: "standards_routines",
    label: "Routines",
    icon: "list-checks",
    route: "/standards/routines",
    feature: "standards_routines",
    rbacAnyOf: ["procedures.view"],
    navVisible: true,
    sortOrder: 200,
    navDomain: "Operations",
    navGroup: "Routines",
    navOrder: 10,
    navAlias: true,
  },
  {
    key: "messaging",
    label: "Messaging",
    icon: "message-square",
    route: "/dashboard/messages",
    feature: "messaging",
    rbacAnyOf: ["messaging.view"],
    navVisible: true,
    sortOrder: 210,
    navDomain: "Operations",
    navGroup: "Communications",
    navOrder: 30,
  },

  // —— Training (workforce learning + compliance) ——
  {
    key: "training_root",
    label: "Training",
    icon: "book-open",
    route: "/training",
    feature: "standards_training",
    rbacAnyOf: [
      "standards.training.view",
      "standards.training.overview.view",
      "standards.training.workers.view",
      "standards.training.certifications.view",
      "standards.training.compliance.view",
      "standards.training.expiring.view",
      "standards.certifications.view",
      "standards.compliance.view",
      "procedures.view",
    ],
    navVisible: false,
    sortOrder: 300,
    navDomain: "Training",
    navGroup: "Training",
    navOrder: 0,
  },
  {
    key: "training_overview",
    label: "Overview",
    icon: "layout",
    route: "/training/overview",
    feature: "standards_training",
    rbacAnyOf: [
      "standards.training.view",
      "standards.training.overview.view",
      "standards.certifications.view",
      "standards.compliance.view",
      "procedures.view",
    ],
    navVisible: false,
    sortOrder: 301,
    navDomain: "Training",
    navGroup: "Training",
    navOrder: 10,
  },
  {
    key: "training_flashcards",
    label: "Flashcards",
    icon: "book-open",
    route: "/training/flashcards",
    feature: "standards_training",
    rbacAnyOf: [
      "standards.training.view",
      "standards.training.overview.view",
      "procedures.view",
    ],
    navVisible: true,
    sortOrder: 301,
    navDomain: "Training",
    navGroup: "Training",
    navOrder: 10,
  },
  {
    key: "training_interviews",
    label: "Interview Prep",
    icon: "book-open",
    route: "/training/interviews",
    feature: "standards_training",
    rbacAnyOf: [
      "standards.training.view",
      "standards.training.overview.view",
      "procedures.view",
    ],
    navVisible: true,
    sortOrder: 301,
    navDomain: "Training",
    navGroup: "Training",
    navOrder: 12,
  },
  {
    key: "training_learning",
    label: "Learning",
    icon: "book-open",
    route: "/training/learning",
    feature: "procedures",
    rbacAnyOf: ["procedures.view", "standards.compliance.view"],
    navVisible: false,
    sortOrder: 302,
    navDomain: "Training",
    navGroup: "Training",
    navOrder: 20,
  },
  {
    key: "training_compliance",
    label: "Compliance",
    icon: "list-checks",
    route: "/training/compliance",
    feature: "standards_compliance",
    rbacAnyOf: [
      "standards.compliance.view",
      "standards.training.compliance.view",
      "standards.training.workers.view",
      "standards.training.certifications.view",
      "standards.training.expiring.view",
    ],
    navVisible: false,
    sortOrder: 303,
    navDomain: "Training",
    navGroup: "Training",
    navOrder: 30,
  },
  /** Legacy registry rows — routes redirect to Training domain; hidden from sidebar. */
  {
    key: "procedures",
    label: "Standards",
    icon: "list-checks",
    route: "/standards",
    feature: "procedures",
    rbacAnyOf: ["procedures.view"],
    navVisible: false,
    sortOrder: 310,
    navDomain: "Training",
    navGroup: "Learning",
    navOrder: 0,
    navAlias: true,
  },
  {
    key: "standards_procedures",
    label: "Procedures",
    icon: "list-checks",
    route: "/standards/procedures",
    feature: "procedures",
    rbacAnyOf: ["procedures.view"],
    navVisible: false,
    sortOrder: 311,
    navDomain: "Training",
    navGroup: "Learning",
    navOrder: 10,
    navAlias: true,
  },
  {
    key: "standards_training",
    label: "Training (legacy)",
    icon: "book-open",
    route: "/standards/training",
    feature: "standards_training",
    rbacAnyOf: [
      "standards.training.view",
      "standards.training.overview.view",
      "standards.training.workers.view",
      "standards.training.certifications.view",
      "standards.training.compliance.view",
      "standards.training.expiring.view",
      "standards.certifications.view",
      "standards.compliance.view",
      "procedures.view",
    ],
    navVisible: false,
    sortOrder: 312,
    navDomain: "Training",
    navGroup: "Training",
    navOrder: 90,
    navAlias: true,
  },
  {
    key: "standards_certifications",
    label: "Certifications",
    icon: "scroll-text",
    route: "/standards/training/certifications",
    feature: "standards_certifications",
    rbacAnyOf: ["standards.certifications.view", "standards.training.certifications.view", "procedures.view"],
    navVisible: false,
    sortOrder: 313,
    navDomain: "Training",
    navGroup: "Compliance",
    navOrder: 20,
    navAlias: true,
  },
  {
    key: "standards_compliance",
    label: "Compliance (legacy)",
    icon: "scroll-text",
    route: "/standards/training/compliance",
    feature: "standards_compliance",
    rbacAnyOf: ["standards.compliance.view", "standards.training.compliance.view", "procedures.view"],
    navVisible: false,
    sortOrder: 314,
    navDomain: "Training",
    navGroup: "Compliance",
    navOrder: 30,
    navAlias: true,
  },
  {
    key: "standards_acknowledgments",
    label: "Acknowledgment archive",
    icon: "scroll-text",
    route: "/standards/acknowledgments",
    feature: "standards_acknowledgments",
    rbacAnyOf: ["standards.compliance.view", "procedures.view"],
    navVisible: false,
    sortOrder: 315,
    navDomain: "Training",
    navGroup: "Learning",
    navOrder: 30,
    navAlias: true,
  },
  {
    key: "standards_my_procedures",
    label: "My procedures",
    icon: "list-checks",
    route: "/standards/my-procedures",
    feature: "standards_my_procedures",
    rbacAnyOf: ["procedures.view"],
    navVisible: false,
    sortOrder: 316,
    navDomain: "Training",
    navGroup: "Learning",
    navOrder: 20,
    dashboardScope: "personal",
    navAlias: true,
  },

  // —— Assets ——
  {
    key: "inventory",
    label: "Inventory",
    icon: "package",
    route: "/dashboard/inventory",
    feature: "inventory",
    rbacAnyOf: ["inventory.view", "inventory.manage"],
    navVisible: true,
    sortOrder: 400,
    navDomain: "Assets",
    navGroup: "Inventory",
    navOrder: 10,
  },
  {
    key: "inventory_scanner",
    label: "Scanner",
    icon: "scan-barcode",
    route: "/kiosk/inventory-scanner",
    feature: "inventory_scanner",
    rbacAnyOf: ["inventory.scan"],
    navVisible: true,
    sortOrder: 405,
    navDomain: "Assets",
    navGroup: "Inventory",
    navOrder: 15,
  },
  {
    key: "purchasing",
    label: "Purchasing",
    icon: "shopping-cart",
    route: "/dashboard/purchasing",
    feature: "inventory",
    rbacAnyOf: ["inventory.view", "inventory.manage"],
    navVisible: false,
    sortOrder: 408,
    navDomain: "Assets",
    navGroup: "Inventory",
    navOrder: 20,
  },
  {
    key: "equipment",
    label: "Equipment",
    icon: "wrench",
    route: "/equipment",
    feature: "equipment",
    rbacAnyOf: ["equipment.view"],
    navVisible: true,
    sortOrder: 410,
    navDomain: "Assets",
    navGroup: "Equipment",
    navOrder: 20,
  },
  {
    key: "zones_devices",
    label: "Zones & Devices",
    icon: "map-pin",
    route: "/devices",
    feature: "zones_devices",
    rbacAnyOf: ["zones_devices.view"],
    navVisible: true,
    sortOrder: 430,
    navDomain: "Assets",
    navGroup: "Zones & Devices",
    navOrder: 40,
  },

  // —— Visuals ——
  {
    key: "drawings",
    label: "Drawings",
    icon: "layers",
    route: "/drawings",
    feature: "drawings",
    rbacAnyOf: ["drawings.view"],
    /** Engine shell route — use Infrastructure maps in nav instead of duplicate “Spatial” entry. */
    navVisible: false,
    sortOrder: 500,
    navDomain: "Visuals",
    navGroup: "Infrastructure",
    navOrder: 10,
  },
  {
    key: "spatial_infrastructure",
    label: "Infrastructure maps",
    icon: "layers",
    route: "/drawings?workspace=infrastructure",
    feature: "spatial_infrastructure",
    rbacAnyOf: ["drawings.view"],
    navVisible: true,
    sortOrder: 501,
    navDomain: "Visuals",
    navGroup: "Infrastructure",
    navOrder: 10,
    navAlias: true,
  },
  {
    key: "facilities_spatial",
    label: "Facilities",
    icon: "building",
    route: "/drawings?workspace=facilities",
    feature: "facilities_spatial",
    rbacAnyOf: ["drawings.view"],
    navVisible: true,
    sortOrder: 505,
    navDomain: "Visuals",
    navGroup: "Facilities",
    navOrder: 25,
    navAlias: true,
  },
  {
    key: "live_map",
    label: "Live Map",
    icon: "radio",
    route: "/live-map",
    feature: "live_map",
    rbacAnyOf: ["live_map.view"],
    navVisible: true,
    sortOrder: 510,
    navDomain: "Visuals",
    navGroup: "Live presence",
    navOrder: 30,
  },
  {
    key: "advertising_mapper",
    label: "Arena Advertising",
    icon: "layout-grid",
    route: "/drawings?workspace=advertising",
    feature: "advertising_mapper",
    rbacAnyOf: ["arena_advertising.view"],
    navVisible: true,
    platformDepartmentSlug: "communications",
    platformRoute: "advertising-mapper",
    sortOrder: 520,
    moduleCategory: "Communications",
    navDomain: "Communications",
    navGroup: "Advertising",
    navOrder: 40,
  },
  {
    key: "xplor_indesign",
    label: "Xplor → InDesign",
    icon: "file-text",
    route: "/communications/indesign-pipeline",
    feature: "xplor_indesign",
    rbacAnyOf: ["xplor_indesign.view"],
    navVisible: true,
    platformDepartmentSlug: "communications",
    platformRoute: "indesign-pipeline",
    sortOrder: 540,
    moduleCategory: "Communications",
    navDomain: "Communications",
    navGroup: "Publications",
    navOrder: 60,
  },
  {
    key: "comms_assets",
    label: "Media assets",
    icon: "image",
    route: "/communications/assets",
    feature: "comms_assets",
    rbacAnyOf: ["communications_assets.view"],
    navVisible: true,
    platformDepartmentSlug: "communications",
    platformRoute: "assets",
    sortOrder: 550,
    moduleCategory: "Communications",
    navDomain: "Communications",
    navGroup: "Assets",
    navOrder: 70,
  },

  // —— Team Management (manager workspace) ——
  {
    key: "workforce_hub",
    label: "Overview",
    icon: "users",
    route: "/team-management",
    feature: "team_management",
    rbacAnyOf: ["team_management.view"],
    navVisible: true,
    sortOrder: 580,
    navDomain: "Team Management",
    navGroup: "Workforce",
    navOrder: 0,
  },
  {
    key: "workforce_people",
    label: "People",
    icon: "users",
    route: "/team-management/people",
    feature: "team_management",
    rbacAnyOf: ["team_management.view"],
    navVisible: true,
    sortOrder: 582,
    navDomain: "Team Management",
    navGroup: "Workforce",
    navOrder: 5,
  },
  {
    key: "workforce_performance",
    label: "Performance",
    icon: "activity",
    route: "/team-management/performance",
    feature: "team_management",
    rbacAnyOf: ["team_management.view"],
    navVisible: true,
    sortOrder: 585,
    navDomain: "Team Management",
    navGroup: "Workforce",
    navOrder: 10,
  },
  {
    key: "workforce_growth",
    label: "Growth",
    icon: "list-checks",
    route: "/team-management/growth",
    feature: "team_management",
    rbacAnyOf: ["team_management.view"],
    navVisible: true,
    sortOrder: 590,
    navDomain: "Team Management",
    navGroup: "Workforce",
    navOrder: 20,
  },
  {
    key: "workforce_planning",
    label: "Planning",
    icon: "calendar",
    route: "/team-management/planning",
    feature: "team_management",
    rbacAnyOf: ["team_management.view"],
    navVisible: true,
    sortOrder: 595,
    navDomain: "Team Management",
    navGroup: "Workforce",
    navOrder: 30,
  },
  {
    key: "workforce_meetings",
    label: "Meetings",
    icon: "clipboard",
    route: "/team-management/meetings",
    feature: "team_management",
    rbacAnyOf: ["team_management.view"],
    navVisible: true,
    sortOrder: 600,
    navDomain: "Team Management",
    navGroup: "Workforce",
    navOrder: 40,
  },
  {
    key: "workforce_insights",
    label: "Team Insights",
    icon: "sparkles",
    route: "/team-management/insights",
    feature: "team_insights",
    rbacAnyOf: [...dashboardRbacAnyOf("dashboard.team_insights.view"), "team_insights.view"],
    navVisible: false,
    sortOrder: 585,
    navDomain: "Team Management",
    navGroup: "Workforce",
    navOrder: 10,
    dashboardScope: "department",
    ownershipDepartment: "maintenance",
  },
  {
    key: "workforce_hiring",
    label: "Hiring",
    icon: "clipboard",
    route: "/team-management/hiring",
    feature: "team_management",
    rbacAnyOf: ["team_management.view"],
    navVisible: false,
    sortOrder: 590,
    navDomain: "Team Management",
    navGroup: "Workforce",
    navOrder: 20,
  },
  {
    key: "workforce_development",
    label: "Development",
    icon: "activity",
    route: "/team-management/development",
    feature: "team_management",
    rbacAnyOf: ["team_management.view"],
    navVisible: false,
    sortOrder: 595,
    navDomain: "Team Management",
    navGroup: "Workforce",
    navOrder: 30,
  },
  {
    key: "workforce_onboarding",
    label: "Onboarding",
    icon: "list-checks",
    route: "/team-management/onboarding",
    feature: "team_management",
    rbacAnyOf: ["team_management.view"],
    navVisible: false,
    sortOrder: 600,
    navDomain: "Team Management",
    navGroup: "Workforce",
    navOrder: 40,
  },
  {
    key: "workforce_recognition",
    label: "Recognition",
    icon: "sparkles",
    route: "/team-management/recognition",
    feature: "team_management",
    rbacAnyOf: ["team_management.view"],
    navVisible: false,
    sortOrder: 605,
    navDomain: "Team Management",
    navGroup: "Workforce",
    navOrder: 50,
  },
  {
    key: "workforce_planning_legacy",
    label: "Workforce Planning",
    icon: "calendar",
    route: "/team-management/workforce-planning",
    feature: "team_management",
    rbacAnyOf: ["team_management.view"],
    navVisible: false,
    sortOrder: 610,
    navDomain: "Team Management",
    navGroup: "Workforce",
    navOrder: 60,
  },
  {
    key: "workforce_coordination",
    label: "Coordination",
    icon: "clipboard",
    route: "/team-management/coordination",
    feature: "team_management",
    rbacAnyOf: ["team_management.view"],
    navVisible: false,
    sortOrder: 615,
    navDomain: "Team Management",
    navGroup: "Workforce",
    navOrder: 70,
  },

  // —— Administration ——
  {
    key: "permissions",
    label: "Permissions",
    icon: "user-cog",
    route: "/dashboard/permissions",
    feature: "team_management",
    rbacAnyOf: ["team_management.view"],
    navVisible: true,
    sortOrder: 620,
    navDomain: "Administration",
    navGroup: "People",
    navOrder: 10,
  },
  {
    key: "qr_codes",
    label: "QR Codes",
    icon: "scan-barcode",
    route: "/dashboard/inventory?tab=qr_codes",
    feature: "qr_codes",
    rbacAnyOf: ["qr_codes.view", "qr_codes.manage"],
    navVisible: false,
    sortOrder: 406,
    navDomain: "Assets",
    navGroup: "Inventory",
    navOrder: 18,
  },
  {
    key: "settings",
    label: "Settings",
    icon: "settings",
    route: "/settings",
    feature: "dashboard",
    rbacAnyOf: [],
    navVisible: true,
    sortOrder: 1000,
    navDomain: "Administration",
    navGroup: "Configuration",
    navOrder: 90,
  },
] as const;

const byKey = new Map(MASTER_FEATURES.map((f) => [f.key, f]));

function normalizeFeatureRoute(route: string): string {
  const path = route.split("?")[0] ?? route;
  if (path.endsWith("/") && path.length > 1) return path.slice(0, -1);
  return path;
}

/** Identity for nav deduplication — preserves query strings when present. */
export function normalizeNavHref(href: string): string {
  const [path, query] = href.split("?");
  const base = normalizeFeatureRoute(path ?? href);
  return query ? `${base}?${query}` : base;
}

const byRoute = new Map(MASTER_FEATURES.map((f) => [normalizeNavHref(f.route), f]));

export function getMasterFeatureByKey(key: string): MasterFeatureDef | undefined {
  return byKey.get(key);
}

export function getMasterFeatureByRoute(route: string): MasterFeatureDef | undefined {
  return byRoute.get(normalizeNavHref(route));
}

/** Longest-prefix match for route guards (e.g. `/standards/procedures` → procedures feature). */
export function getMasterFeatureForPath(pathname: string): MasterFeatureDef | undefined {
  const [pathPart, queryPart] = pathname.split("?");
  const h = normalizeFeatureRoute(pathPart ?? pathname);
  const withQuery = queryPart ? `${h}?${queryPart}` : h;

  const exact = byRoute.get(withQuery) ?? byRoute.get(h);
  if (exact) return exact;

  let best: MasterFeatureDef | undefined;
  let bestLen = -1;
  for (const f of MASTER_FEATURES) {
    const r = normalizeFeatureRoute(f.route);
    if (h === r || h.startsWith(`${r}/`)) {
      if (r.length > bestLen) {
        bestLen = r.length;
        best = f;
      }
    }
  }
  return best;
}

export const NAV_VISIBLE_MASTER_FEATURES = MASTER_FEATURES.filter((f) => f.navVisible);
