"""RBAC catalog: flat permission keys and mapping from legacy company feature / product keys."""

from __future__ import annotations

# Keys mirrored in `rbac_catalog_permissions` via `app.core.rbac.catalog_sync` at runtime (and legacy Alembic seeds).
RBAC_PERMISSION_SEED: tuple[tuple[str, str], ...] = (
    ("dashboard.view", "View leadership / operations dashboard"),
    ("work_requests.view", "View work requests"),
    ("work_requests.edit", "Edit work requests"),
    ("compliance.view", "View inspections & compliance"),
    ("compliance.manage", "Manage compliance records (review, resend, flag)"),
    ("inventory.view", "View inventory"),
    ("inventory.manage", "Manage inventory"),
    ("equipment.view", "View equipment"),
    ("equipment.manage", "Manage equipment registry and parts"),
    ("procedures.view", "View procedures / standards"),
    ("team_insights.view", "View team insights / analytics"),
    ("team_management.view", "Open Team Management"),
    ("messaging.view", "View messaging"),
    ("schedule.view", "View scheduling / classes"),
    ("monitoring.view", "View monitoring"),
    ("projects.view", "View projects"),
    ("drawings.view", "View drawings"),
    ("zones_devices.view", "View zones & devices"),
    ("live_map.view", "View live map"),
    ("arena_advertising.view", "Arena advertising mapper"),
    ("social_planner.view", "Social / campaign planner"),
    ("publication_pipeline.view", "Publication pipeline"),
    ("xplor_indesign.view", "Xplor → InDesign export"),
    ("communications_assets.view", "Communications assets library"),
)

# Legacy `company_features` / `GLOBAL_SYSTEM_FEATURES` name → flat RBAC keys (bridge until grants-only).
FEATURE_TO_RBAC_PERMISSIONS: dict[str, tuple[str, ...]] = {
    "dashboard": ("dashboard.view",),
    "work_requests": ("work_requests.view", "work_requests.edit"),
    "compliance": ("compliance.view", "compliance.manage"),
    "logs_inspections": ("compliance.view", "compliance.manage"),
    "standards": ("procedures.view",),
    "advertising_mapper": ("arena_advertising.view",),
    "xplor_indesign": ("xplor_indesign.view",),
    "procedures": ("procedures.view",),
    "inventory": ("inventory.view", "inventory.manage"),
    "equipment": ("equipment.view",),
    "team_insights": ("team_insights.view",),
    "team_management": ("team_management.view",),
    "messaging": ("messaging.view",),
    "schedule": ("schedule.view",),
    "monitoring": ("monitoring.view",),
    "projects": ("projects.view",),
    "drawings": ("drawings.view",),
    "zones_devices": ("zones_devices.view",),
    "live_map": ("live_map.view",),
    "comms_advertising_mapper": ("arena_advertising.view",),
    "comms_campaign_planner": ("social_planner.view",),
    "comms_publication_builder": ("publication_pipeline.view",),
    "comms_indesign_pipeline": ("xplor_indesign.view",),
    "comms_assets": ("communications_assets.view",),
}

# RBAC key must only apply if the tenant contract includes this feature key (subset of GLOBAL / company_features).
RBAC_KEY_REQUIRES_COMPANY_FEATURE: dict[str, str | None] = {
    "dashboard.view": "dashboard",
    "work_requests.view": "work_requests",
    "work_requests.edit": "work_requests",
    "compliance.view": "compliance",
    "compliance.manage": "compliance",
    "inventory.view": "inventory",
    "inventory.manage": "inventory",
    "equipment.view": "equipment",
    "equipment.manage": "equipment",
    "procedures.view": "procedures",
    "team_insights.view": "team_insights",
    "team_management.view": "team_management",
    "messaging.view": "messaging",
    "schedule.view": "schedule",
    "monitoring.view": "monitoring",
    "projects.view": "projects",
    "drawings.view": "drawings",
    "zones_devices.view": "zones_devices",
    "live_map.view": "live_map",
    "arena_advertising.view": "comms_advertising_mapper",
    "social_planner.view": "comms_campaign_planner",
    "publication_pipeline.view": "comms_publication_builder",
    "xplor_indesign.view": "comms_indesign_pipeline",
    "communications_assets.view": "comms_assets",
}
