"""RBAC catalog: flat permission keys and mapping from legacy company feature / product keys."""

from __future__ import annotations

# Keys mirrored in `rbac_catalog_permissions` via `app.core.rbac.catalog_sync` at runtime (and legacy Alembic seeds).
RBAC_PERMISSION_SEED: tuple[tuple[str, str], ...] = (
    ("dashboard.view", "View all dashboards (legacy umbrella)"),
    ("dashboard.operations.view", "Operations dashboard (/worker)"),
    ("dashboard.leadership.view", "Leadership dashboard (/overview)"),
    ("dashboard.project.view", "Project dashboard (/overview/project)"),
    ("dashboard.inspections.view", "Inspections & logs dashboard flyout"),
    ("dashboard.team_insights.view", "Team insights dashboard flyout"),
    ("dashboard.kiosk.view", "Kiosk display routes (/kiosk/*)"),
    ("dashboard.dept.communications.view", "Communications department dashboard"),
    ("dashboard.dept.aquatics.view", "Aquatics department dashboard"),
    ("dashboard.dept.reception.view", "Reception department dashboard"),
    ("dashboard.dept.fitness.view", "Fitness department dashboard"),
    ("dashboard.dept.racquets.view", "Racquets department dashboard"),
    ("dashboard.dept.admin.view", "Administration department dashboard"),
    ("work_requests.view", "View work requests"),
    ("work_requests.edit", "Edit work requests"),
    ("compliance.view", "View inspections & compliance"),
    ("compliance.manage", "Manage compliance records (review, resend, flag)"),
    ("inventory.view", "View inventory"),
    ("inventory.manage", "Manage inventory"),
    ("equipment.view", "View equipment"),
    ("equipment.manage", "Manage equipment registry and parts"),
    ("procedures.view", "View procedures / standards"),
    ("procedures.edit", "Edit procedures / standards"),
    ("team_insights.view", "View team insights / analytics"),
    ("team_management.view", "Open Team Management"),
    ("messaging.view", "View messaging"),
    ("schedule.view", "View scheduling / classes"),
    ("scheduling.project_overlays.view", "View project timeline overlays on schedule"),
    ("scheduling.pto_conflict_visibility.view", "View PTO vs project staffing conflict hints"),
    ("monitoring.view", "View monitoring"),
    ("projects.view", "View projects"),
    ("projects.pm.view", "PM workspace and planning tools"),
    ("drawings.view", "View drawings"),
    ("zones_devices.view", "View zones & devices"),
    ("live_map.view", "View live map"),
    ("arena_advertising.view", "Arena advertising mapper"),
    ("social_planner.view", "Social / campaign planner"),
    ("xplor_indesign.view", "Xplor → InDesign export"),
    ("communications_assets.view", "Communications assets library"),
)

# Legacy `company_features` / `GLOBAL_SYSTEM_FEATURES` name → flat RBAC keys (bridge until grants-only).
FEATURE_TO_RBAC_PERMISSIONS: dict[str, tuple[str, ...]] = {
    "dashboard": ("dashboard.view",),
    "dashboard_operations": ("dashboard.operations.view",),
    "dashboard_leadership": ("dashboard.leadership.view",),
    "dashboard_project": ("dashboard.project.view",),
    "dashboard_inspections": ("dashboard.inspections.view",),
    "dashboard_team_insights": ("dashboard.team_insights.view",),
    "dashboard_dept_communications": ("dashboard.dept.communications.view",),
    "dashboard_dept_aquatics": ("dashboard.dept.aquatics.view",),
    "dashboard_dept_reception": ("dashboard.dept.reception.view",),
    "dashboard_dept_fitness": ("dashboard.dept.fitness.view",),
    "dashboard_dept_racquets": ("dashboard.dept.racquets.view",),
    "dashboard_dept_admin": ("dashboard.dept.admin.view",),
    "work_requests": ("work_requests.view",),
    "compliance": ("compliance.view", "compliance.manage"),
    "logs_inspections": ("compliance.view", "compliance.manage"),
    "standards": ("procedures.view",),
    "advertising_mapper": ("arena_advertising.view",),
    "xplor_indesign": ("xplor_indesign.view",),
    "procedures": ("procedures.view", "procedures.edit"),
    "inventory": ("inventory.view", "inventory.manage"),
    "equipment": ("equipment.view",),
    "team_insights": ("team_insights.view",),
    "team_management": ("team_management.view",),
    "messaging": ("messaging.view",),
    "schedule": (
        "schedule.view",
        "scheduling.project_overlays.view",
        "scheduling.pto_conflict_visibility.view",
    ),
    "monitoring": ("monitoring.view",),
    "projects": ("projects.view",),
    "drawings": ("drawings.view",),
    "zones_devices": ("zones_devices.view",),
    "live_map": ("live_map.view",),
    "comms_advertising_mapper": ("arena_advertising.view",),
    "comms_campaign_planner": ("social_planner.view",),
    "comms_indesign_pipeline": ("xplor_indesign.view",),
    "comms_assets": ("communications_assets.view",),
}

# RBAC key must only apply if the tenant contract includes this feature key (subset of GLOBAL / company_features).
RBAC_KEY_REQUIRES_COMPANY_FEATURE: dict[str, str | None] = {
    "dashboard.view": "dashboard",
    "dashboard.operations.view": "dashboard",
    "dashboard.leadership.view": "dashboard",
    "dashboard.project.view": "dashboard",
    "dashboard.inspections.view": "dashboard",
    "dashboard.team_insights.view": "dashboard",
    "dashboard.kiosk.view": "dashboard",
    "dashboard.dept.communications.view": "dashboard",
    "dashboard.dept.aquatics.view": "dashboard",
    "dashboard.dept.reception.view": "dashboard",
    "dashboard.dept.fitness.view": "dashboard",
    "dashboard.dept.racquets.view": "dashboard",
    "dashboard.dept.admin.view": "dashboard",
    "work_requests.view": "work_requests",
    "work_requests.edit": "work_requests",
    "compliance.view": "compliance",
    "compliance.manage": "compliance",
    "inventory.view": "inventory",
    "inventory.manage": "inventory",
    "equipment.view": "equipment",
    "equipment.manage": "equipment",
    "procedures.view": "procedures",
    "procedures.edit": "procedures",
    "team_insights.view": "team_insights",
    "team_management.view": "team_management",
    "messaging.view": "messaging",
    "schedule.view": "schedule",
    "scheduling.project_overlays.view": "schedule",
    "scheduling.pto_conflict_visibility.view": "schedule",
    "monitoring.view": "monitoring",
    "projects.view": "projects",
    "projects.pm.view": "projects",
    "drawings.view": "drawings",
    "zones_devices.view": "zones_devices",
    "live_map.view": "live_map",
    "arena_advertising.view": "comms_advertising_mapper",
    "social_planner.view": "comms_campaign_planner",
    "xplor_indesign.view": "comms_indesign_pipeline",
    "publication_pipeline.view": "comms_indesign_pipeline",
    "communications_assets.view": "comms_assets",
}
