"use client";

import { Award } from "lucide-react";
import { flushSync } from "react-dom";
import { scheduleShiftHoverSummary, shiftHasCertificationFlag } from "@/lib/schedule/certifications";
import { getShiftConflicts, worstConflictSeverity } from "@/lib/schedule/conflicts";
import type { CompactDayShiftRow } from "@/lib/schedule/compact-day-shifts";
import {
  attachShiftDragPreview,
  setShiftDragData,
} from "@/lib/schedule/drag";
import type {
  ScheduleDragSession,
  ScheduleRoleDefinition,
  ScheduleSettings,
  Shift,
  ShiftTypeConfig,
  TimeOffBlock,
  Worker,
  Zone,
} from "@/lib/schedule/types";

type Props = {
  rows: CompactDayShiftRow[];
  fullDayShifts: Shift[];
  workers: Worker[];
  zones: Zone[];
  roles: ScheduleRoleDefinition[];
  shiftTypes: ShiftTypeConfig[];
  settings: ScheduleSettings;
  timeOffBlocks: TimeOffBlock[];
  onSelectShift: (shift: Shift) => void;
  scheduleDragLock: boolean;
  dragSession: ScheduleDragSession | null;
  shiftDragEnabled?: boolean;
  onShiftDragSessionStart: (payload: ScheduleDragSession) => void;
  onShiftDragSessionEnd: () => void;
  /** Outer scroll area (month vs week cell height). */
  scrollClassName?: string;
  /**
   * `summary` — one line per chip (name · shift code only); full role/zone/time open in day view or shift editor.
   * `full` — second line with role · zone (or project line).
   */
  chipDetailLevel?: "summary" | "full";
};

function aggregateConflictUi(
  row: CompactDayShiftRow,
  fullDay: Shift[],
  workers: Worker[],
  settings: ScheduleSettings,
  timeOffBlocks: TimeOffBlock[],
  zones: Zone[],
  workerMap: Map<string, Worker>,
) {
  let worst: ReturnType<typeof worstConflictSeverity> = null;
  let anyCert = false;
  const tips: string[] = [];
  for (const s of row.shifts) {
    const w = s.workerId ? workerMap.get(s.workerId) : null;
    const c = getShiftConflicts(s, fullDay, workers, settings, timeOffBlocks, zones);
    const sev = worstConflictSeverity(c);
    if (sev === "critical" || (sev === "warning" && worst !== "critical")) worst = sev;
    if (shiftHasCertificationFlag(c)) anyCert = true;
    tips.push(scheduleShiftHoverSummary(s, w ?? null, c));
  }
  return { worst, anyCert, tip: tips.filter(Boolean).join("\n---\n") };
}

export function ScheduleCompactCellRows({
  rows,
  fullDayShifts,
  workers,
  zones,
  roles,
  shiftTypes,
  settings,
  timeOffBlocks,
  onSelectShift,
  scheduleDragLock,
  dragSession,
  shiftDragEnabled = true,
  onShiftDragSessionStart,
  onShiftDragSessionEnd,
  scrollClassName = "max-h-[11rem] flex-1 flex-col gap-1 overflow-y-auto px-1 pb-2 pt-1",
  chipDetailLevel = "full",
}: Props) {
  const typeMap = new Map(shiftTypes.map((t) => [t.key, t]));
  const zoneMap = new Map(zones.map((z) => [z.id, z.label]));
  const roleMap = new Map(roles.map((r) => [r.id, r.label]));
  const workerMap = new Map(workers.map((w) => [w.id, w]));

  const summary = chipDetailLevel === "summary";

  return (
    <div className={`relative z-[2] flex ${scrollClassName}`}>
      {rows.map((row) => {
        const s = row.primaryShift;
        const st = typeMap.get(s.shiftType);
        const w = s.workerId ? workerMap.get(s.workerId) : null;
        const isOpen = !s.workerId && s.shiftKind !== "project_task";
        const zone = zoneMap.get(s.zoneId) ?? "—";
        const roleLb = roleMap.get(s.role) ?? s.role;
        const cls = st
          ? `${st.bg} ${st.border} ${st.text} border`
          : "border border-pulseShell-border bg-pulseShell-elevated text-ds-foreground";
        const ptoCls =
          s.eventType === "vacation"
            ? "border-[color-mix(in_srgb,var(--ds-warning)_38%,var(--ds-border))] bg-[color-mix(in_srgb,var(--ds-warning)_18%,var(--ds-surface-primary))] text-ds-foreground"
            : s.eventType === "sick"
              ? "border-[color-mix(in_srgb,var(--ds-danger)_32%,var(--ds-border))] bg-[color-mix(in_srgb,var(--ds-danger)_15%,var(--ds-surface-primary))] text-ds-foreground"
              : "";
        const chipBaseCls = ptoCls || cls;
        const openCls = isOpen
          ? "ring-2 ring-dashed ring-ds-success/45 ring-offset-1 ring-offset-pulse-shell-cell dark:ring-offset-pulse-shell-cell"
          : "";
        const { worst, anyCert, tip } = aggregateConflictUi(
          row,
          fullDayShifts,
          workers,
          settings,
          timeOffBlocks,
          zones,
          workerMap,
        );
        const chipLocked =
          scheduleDragLock &&
          (dragSession?.kind === "worker" ||
            (dragSession?.kind === "shift" && !row.shifts.some((x) => x.id === dragSession.shiftId)));
        const anyAuto = row.shifts.some((x) => x.autoGenerated);
        const canDrag =
          shiftDragEnabled &&
          !anyAuto &&
          row.shifts.length === 1 &&
          (!scheduleDragLock || (dragSession?.kind === "shift" && dragSession.shiftId === s.id));

        return (
          <div
            key={row.key}
            role="button"
            tabIndex={0}
            data-schedule-interactive
            draggable={canDrag}
            className={`w-full rounded-lg text-left shadow-sm transition-colors hover:brightness-[0.97] ${
              summary ? "px-1 py-0.5 text-[10px] leading-tight" : "px-1.5 py-1.5 text-[11px] leading-snug"
            } ${anyAuto ? "opacity-[0.92]" : ""} ${canDrag ? "cursor-grab active:cursor-grabbing" : "cursor-default"} ${chipLocked ? "pointer-events-none" : ""} ${chipBaseCls} ${openCls}`}
            onClick={(e) => {
              e.stopPropagation();
              if (scheduleDragLock || anyAuto) return;
              onSelectShift(s);
            }}
            onKeyDown={(e) => {
              e.stopPropagation();
              if (scheduleDragLock || anyAuto) return;
              if (e.key === "Enter" || e.key === " ") {
                e.preventDefault();
                onSelectShift(s);
              }
            }}
            onDragStart={(e) => {
              if (!shiftDragEnabled || anyAuto || row.shifts.length !== 1) {
                e.preventDefault();
                return;
              }
              const dup = e.shiftKey;
              setShiftDragData(e.dataTransfer, { shiftId: s.id, duplicate: dup });
              attachShiftDragPreview(e, dup);
              flushSync(() => onShiftDragSessionStart({ kind: "shift", shiftId: s.id, duplicate: dup }));
            }}
            onDragEnd={onShiftDragSessionEnd}
          >
            <div className={`flex items-center justify-between gap-1 ${summary ? "" : "items-start"}`}>
              <div className="min-w-0 flex-1">
                <p className="truncate font-semibold leading-tight">{row.title}</p>
                {!summary ? (
                  <>
                    {row.shifts.length > 1 ? (
                      <p className="truncate text-[10px] opacity-80">{row.shifts.length} blocks — tap to edit first</p>
                    ) : s.shiftKind === "project_task" && s.projectName ? (
                      <p className="truncate text-[10px] opacity-90">{s.projectName}</p>
                    ) : (
                      <p className="truncate text-[10px] opacity-90">
                        {s.shiftKind === "project_task" ? "Project" : `${roleLb} · ${zone}`}
                      </p>
                    )}
                  </>
                ) : row.shifts.length > 1 ? (
                  <p className="truncate text-[9px] opacity-75">{row.shifts.length} blocks</p>
                ) : null}
              </div>
              <div className={`flex shrink-0 items-center gap-0.5 ${summary ? "flex-row" : "flex-col items-end gap-0.5"}`}>
                {!summary && anyAuto ? (
                  <span className="text-[8px] font-bold uppercase text-ds-muted">Auto</span>
                ) : null}
                {!summary && row.shifts.length === 1 && s.uiFlags?.isNew ? (
                  <span className="text-[8px] font-bold uppercase text-ds-success">New</span>
                ) : null}
                {!summary && row.shifts.length === 1 && s.uiFlags?.isUpdated ? (
                  <span className="text-[8px] font-bold uppercase text-ds-warning">Chg</span>
                ) : null}
                <div className="flex items-center gap-0.5">
                  {anyCert ? (
                    <span title={tip} className="inline-flex">
                      <Award className={`shrink-0 text-ds-muted ${summary ? "h-2.5 w-2.5" : "h-3 w-3"}`} strokeWidth={2} aria-hidden />
                    </span>
                  ) : null}
                  {worst ? (
                    <span
                      title={tip}
                      className={`inline-block shrink-0 rounded-full ${summary ? "h-1.5 w-1.5" : "h-2 w-2"} ${
                        worst === "critical" ? "bg-ds-danger" : "bg-ds-warning"
                      }`}
                      aria-label={tip}
                    />
                  ) : null}
                </div>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}
