"use client";

import { flushSync } from "react-dom";
import { scheduleShiftHoverSummary } from "@/lib/schedule/certifications";
import { getShiftConflicts, worstConflictSeverity } from "@/lib/schedule/conflicts";
import type { CompactDayShiftRow } from "@/lib/schedule/compact-day-shifts";
import {
  attachShiftDragPreview,
  setShiftDragData,
} from "@/lib/schedule/drag";
import { buildingIndicatorForZone } from "@/lib/schedule/building-indicators";
import { ScheduleShiftCertChips } from "./ScheduleShiftCertChips";
import type {
  ScheduleDragSession,
  ScheduleRoleDefinition,
  ScheduleSettings,
  Shift,
  ShiftTypeConfig,
  TimeOffBlock,
  Worker,
  Zone,
} from "@/lib/schedule/types";

type Props = {
  rows: CompactDayShiftRow[];
  fullDayShifts: Shift[];
  workers: Worker[];
  zones: Zone[];
  roles: ScheduleRoleDefinition[];
  shiftTypes: ShiftTypeConfig[];
  settings: ScheduleSettings;
  timeOffBlocks: TimeOffBlock[];
  onSelectShift: (shift: Shift) => void;
  scheduleDragLock: boolean;
  dragSession: ScheduleDragSession | null;
  shiftDragEnabled?: boolean;
  onShiftDragSessionStart: (payload: ScheduleDragSession) => void;
  onShiftDragSessionEnd: () => void;
  /** Outer scroll area (month vs week cell height). */
  scrollClassName?: string;
  /**
   * `summary` — one line per chip (name · shift code only); full role/facility/time open in day view or shift editor.
   * `full` — second line with role · facility (or project line).
   */
  chipDetailLevel?: "summary" | "full";
};

function aggregateConflictUi(
  row: CompactDayShiftRow,
  fullDay: Shift[],
  workers: Worker[],
  settings: ScheduleSettings,
  timeOffBlocks: TimeOffBlock[],
  zones: Zone[],
  workerMap: Map<string, Worker>,
) {
  let worst: ReturnType<typeof worstConflictSeverity> = null;
  const tips: string[] = [];
  for (const s of row.shifts) {
    const w = s.workerId ? workerMap.get(s.workerId) : null;
    const c = getShiftConflicts(s, fullDay, workers, settings, timeOffBlocks, zones);
    const sev = worstConflictSeverity(c);
    if (sev === "critical" || (sev === "warning" && worst !== "critical")) worst = sev;
    tips.push(scheduleShiftHoverSummary(s, w ?? null, c));
  }
  return { worst, tip: tips.filter(Boolean).join("\n---\n") };
}

export function ScheduleCompactCellRows({
  rows,
  fullDayShifts,
  workers,
  zones,
  roles,
  shiftTypes,
  settings,
  timeOffBlocks,
  onSelectShift,
  scheduleDragLock,
  dragSession,
  shiftDragEnabled = true,
  onShiftDragSessionStart,
  onShiftDragSessionEnd,
  scrollClassName = "max-h-[11rem] flex-1 flex-col gap-1 overflow-y-auto px-1 pb-2 pt-1",
  chipDetailLevel = "full",
}: Props) {
  const typeMap = new Map(shiftTypes.map((t) => [t.key, t]));
  const zoneMap = new Map(zones.map((z) => [z.id, z.label]));
  const zoneObjMap = new Map(zones.map((z) => [z.id, z]));
  const roleMap = new Map(roles.map((r) => [r.id, r.label]));
  const workerMap = new Map(workers.map((w) => [w.id, w]));

  const summary = chipDetailLevel === "summary";

  return (
    <div className={`relative z-[2] flex ${scrollClassName}`}>
      {rows.map((row) => {
        const s = row.primaryShift;
        const st = typeMap.get(s.shiftType);
        const isOpen = !s.workerId && s.shiftKind !== "project_task";
        const zone = zoneMap.get(s.zoneId) ?? "—";
        const zoneObj = zoneObjMap.get(s.zoneId);
        const bld = buildingIndicatorForZone(zoneObj);
        const roleLb = roleMap.get(s.role) ?? s.role;
        // Outer card stays neutral; shift chip carries the shift-type color for compact scan.
        const cardCls = "border border-pulseShell-border bg-pulseShell-surface text-ds-foreground";
        const openCls = isOpen
          ? "ring-2 ring-dashed ring-ds-success/45 ring-offset-1 ring-offset-pulse-shell-cell dark:ring-offset-pulse-shell-cell"
          : "";
        const { worst, tip } = aggregateConflictUi(
          row,
          fullDayShifts,
          workers,
          settings,
          timeOffBlocks,
          zones,
          workerMap,
        );
        const chipLocked =
          scheduleDragLock &&
          (dragSession?.kind === "worker" ||
            (dragSession?.kind === "shift" && !row.shifts.some((x) => x.id === dragSession.shiftId)));
        const anyAuto = row.shifts.some((x) => x.autoGenerated);
        const canDrag =
          shiftDragEnabled &&
          !anyAuto &&
          row.shifts.length === 1 &&
          (!scheduleDragLock || (dragSession?.kind === "shift" && dragSession.shiftId === s.id));

        const certUnion = [
          ...new Set(
            row.shifts.flatMap((x) => (x.required_certifications?.filter(Boolean) as string[] | undefined) ?? []),
          ),
        ] as string[];

        return (
          <div
            key={row.key}
            role="button"
            tabIndex={0}
            data-schedule-interactive
            draggable={canDrag}
            className={`w-full rounded-lg text-left shadow-sm transition-colors hover:brightness-[0.97] ${
              summary ? "px-1 py-px text-[10px] leading-tight" : "px-1.5 py-1.5 text-[11px] leading-snug"
            } ${anyAuto ? "opacity-[0.92]" : ""} ${canDrag ? "cursor-grab active:cursor-grabbing" : "cursor-default"} ${chipLocked ? "pointer-events-none" : ""} ${cardCls} ${openCls}`}
            onClick={(e) => {
              e.stopPropagation();
              if (scheduleDragLock || anyAuto) return;
              onSelectShift(s);
            }}
            onKeyDown={(e) => {
              e.stopPropagation();
              if (scheduleDragLock || anyAuto) return;
              if (e.key === "Enter" || e.key === " ") {
                e.preventDefault();
                onSelectShift(s);
              }
            }}
            onDragStart={(e) => {
              if (!shiftDragEnabled || anyAuto || row.shifts.length !== 1) {
                e.preventDefault();
                return;
              }
              const dup = e.shiftKey;
              setShiftDragData(e.dataTransfer, { shiftId: s.id, duplicate: dup });
              attachShiftDragPreview(e, dup);
              flushSync(() => onShiftDragSessionStart({ kind: "shift", shiftId: s.id, duplicate: dup }));
            }}
            onDragEnd={onShiftDragSessionEnd}
          >
            <div className="min-w-0">
              {summary ? (
                <div className="flex min-w-0 items-center gap-0.5">
                  <span className="min-w-0 flex-1 truncate font-semibold leading-tight">{row.name}</span>
                  <span className="flex min-w-0 shrink-0 items-center gap-0.5">
                    {certUnion.length ? (
                      <ScheduleShiftCertChips shift={s} size="compact" requiredOverride={certUnion} />
                    ) : null}
                    {bld ? (
                      <span className="inline-flex shrink-0 items-center rounded border border-pulseShell-border bg-pulseShell-elevated/40 px-1 py-px text-[9px] font-bold leading-none text-ds-muted">
                        {bld.code}
                      </span>
                    ) : null}
                    <span
                      className={`ml-auto inline-flex shrink-0 items-center rounded border px-1 py-px text-[9px] font-bold leading-none ${
                        st ? `${st.bg} ${st.border} ${st.text}` : "border-pulseShell-border bg-pulseShell-elevated text-ds-foreground"
                      }`}
                    >
                      {row.code}
                    </span>
                    {worst ? (
                      <span
                        title={tip}
                        className={`inline-block shrink-0 rounded-full h-1.5 w-1.5 ${
                          worst === "critical" ? "bg-ds-danger" : "bg-ds-warning"
                        }`}
                        aria-label={tip}
                      />
                    ) : null}
                  </span>
                </div>
              ) : (
                <>
                  <p className="truncate font-semibold leading-tight">{row.name}</p>

                  <div className="mt-0.5 flex w-full min-w-0 flex-wrap items-center justify-end gap-1">
                    {certUnion.length ? <ScheduleShiftCertChips shift={s} size="day" requiredOverride={certUnion} /> : null}
                    {bld ? (
                      <span className="inline-flex shrink-0 items-center rounded-md border border-pulseShell-border bg-pulseShell-elevated/40 px-1.5 py-0.5 text-[10px] font-bold leading-none text-ds-muted">
                        {bld.code}
                      </span>
                    ) : null}
                    <span
                      className={`ml-auto inline-flex shrink-0 items-center rounded-md border px-1.5 py-0.5 text-[10px] font-bold leading-none ${
                        st ? `${st.bg} ${st.border} ${st.text}` : "border-pulseShell-border bg-pulseShell-elevated text-ds-foreground"
                      }`}
                    >
                      {row.code}
                    </span>
                    {worst ? (
                      <span
                        title={tip}
                        className={`inline-block shrink-0 rounded-full h-2 w-2 ${
                          worst === "critical" ? "bg-ds-danger" : "bg-ds-warning"
                        }`}
                        aria-label={tip}
                      />
                    ) : null}
                  </div>
                </>
              )}

              {!summary ? (
                <>
                  {row.shifts.length > 1 ? (
                    <p className="mt-1 truncate text-[10px] opacity-80">{row.shifts.length} blocks — tap to edit first</p>
                  ) : s.shiftKind === "project_task" && s.projectName ? (
                    <p className="mt-1 truncate text-[10px] opacity-90">{s.projectName}</p>
                  ) : (
                    <p className="mt-1 truncate text-[10px] opacity-90">
                      {s.shiftKind === "project_task" ? "Project" : `${roleLb} · ${zone}`}
                    </p>
                  )}
                </>
              ) : row.shifts.length > 1 ? (
                <p className="mt-0.5 truncate text-[9px] opacity-75">{row.shifts.length} blocks</p>
              ) : null}
            </div>
          </div>
        );
      })}
    </div>
  );
}
