import type {
  CalendarLayerItem,
  Campaign,
  CrossDepartmentRequest,
  FacilityWallLayout,
} from "@/modules/communications/types";

export const MOCK_FACILITY_WALLS: FacilityWallLayout[] = [
  {
    id: "arena-north",
    name: "Arena North Wall",
    aspectRatio: 4.2,
    gridCols: 24,
    slots: [
      {
        id: "n-1",
        name: "North ribbon A",
        x: 4,
        y: 12,
        width: 18,
        height: 38,
        status: "occupied",
        sponsorName: "River City Credit Union",
        expiryDate: "2026-09-01",
      },
      {
        id: "n-2",
        name: "North ribbon B",
        x: 26,
        y: 12,
        width: 18,
        height: 38,
        status: "reserved",
        sponsorName: "Peak Athletics",
      },
      {
        id: "n-3",
        name: "North center board",
        x: 48,
        y: 8,
        width: 28,
        height: 52,
        status: "available",
      },
      {
        id: "n-4",
        name: "North ribbon C",
        x: 78,
        y: 12,
        width: 18,
        height: 38,
        status: "expired",
        sponsorName: "Winter Fest 2025",
        expiryDate: "2025-12-15",
      },
    ],
  },
  {
    id: "arena-south",
    name: "Arena South Wall",
    aspectRatio: 4.2,
    gridCols: 24,
    slots: [
      {
        id: "s-1",
        name: "South marquee",
        x: 8,
        y: 10,
        width: 36,
        height: 48,
        status: "occupied",
        sponsorName: "Municipal Aquatics",
        expiryDate: "2026-11-20",
      },
      {
        id: "s-2",
        name: "South flank",
        x: 52,
        y: 18,
        width: 40,
        height: 36,
        status: "available",
      },
    ],
  },
  {
    id: "lobby-banners",
    name: "Lobby Banner Area",
    aspectRatio: 2.4,
    gridCols: 16,
    slots: [
      {
        id: "l-1",
        name: "Lobby A",
        x: 6,
        y: 20,
        width: 26,
        height: 56,
        status: "reserved",
      },
      {
        id: "l-2",
        name: "Lobby B",
        x: 38,
        y: 20,
        width: 26,
        height: 56,
        status: "available",
      },
      {
        id: "l-3",
        name: "Lobby C",
        x: 70,
        y: 20,
        width: 22,
        height: 56,
        status: "occupied",
        sponsorName: "Community Foundation",
        expiryDate: "2026-04-01",
      },
    ],
  },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "cmp-1",
    title: "Summer Registration",
    department: "Communications",
    startDate: "2026-05-01",
    endDate: "2026-08-31",
    status: "design",
    channels: ["Web", "Print", "Arena signage"],
    assignedTo: ["Jordan", "Sam"],
    assets: ["hero-photo-draft.jpg", "copy-v2.txt"],
    description: "Cross-channel push for summer programs and early-bird pricing.",
    deadlines: [
      { label: "Copy lock", date: "2026-05-15" },
      { label: "Print proof", date: "2026-05-22" },
    ],
  },
  {
    id: "cmp-2",
    title: "Swim Lessons",
    department: "Aquatics",
    startDate: "2026-06-01",
    endDate: "2026-07-15",
    status: "scheduled",
    channels: ["Social", "Email", "Facility screens"],
    assignedTo: ["Alex"],
    description: "Lesson blocks and instructor spotlight series.",
  },
  {
    id: "cmp-3",
    title: "Fitness Challenge",
    department: "Fitness",
    startDate: "2026-05-20",
    endDate: "2026-06-30",
    status: "planning",
    channels: ["Social", "In-club"],
    assignedTo: ["Riley", "Morgan"],
  },
  {
    id: "cmp-4",
    title: "Arena Closure Notice",
    department: "Communications",
    startDate: "2026-05-10",
    endDate: "2026-05-18",
    status: "published",
    channels: ["Web", "Arena", "Email"],
    description: "Coordinated downtime messaging for ice conversion.",
  },
];

export const MOCK_CALENDAR_LAYER: CalendarLayerItem[] = [
  { id: "lay-1", kind: "campaign", title: "Summer Registration", startDate: "2026-05-01", endDate: "2026-08-31", accent: "sky" },
  { id: "lay-2", kind: "event", title: "Youth tournament weekend", startDate: "2026-05-24", endDate: "2026-05-25", accent: "violet" },
  { id: "lay-3", kind: "facility_notice", title: "Pool chemical service", startDate: "2026-05-12", endDate: "2026-05-12", accent: "amber" },
  { id: "lay-4", kind: "closure", title: "Arena partial close", startDate: "2026-05-10", endDate: "2026-05-12", accent: "rose" },
];

export const MOCK_CROSS_DEPT_REQUESTS: CrossDepartmentRequest[] = [
  {
    id: "req-1",
    fromDepartment: "Aquatics",
    summary: "Poster + social kit for masters swim block",
    status: "open",
    createdAt: "2026-05-02",
  },
  {
    id: "req-2",
    fromDepartment: "Fitness",
    summary: "Challenge leaderboard template for lobby screens",
    status: "in_review",
    createdAt: "2026-04-28",
  },
  {
    id: "req-3",
    fromDepartment: "Arena",
    summary: "Wayfinding update for tournament ingress",
    status: "scheduled",
    createdAt: "2026-04-20",
  },
];
