import type { WorkRequest } from "@/types/cmms";

/** Seed data — replace with API (`GET /api/v1/work-requests`) when wired. */
export const WORK_REQUESTS_SEED: WorkRequest[] = [
  {
    id: "wr-8921",
    status: "overdue",
    priority: "urgent",
    asset: { id: "AST-HVAC-04", label: "HVAC Compressor #4" },
    location: "Plant A — Roof",
    category: "HVAC",
    description: "Vibration past threshold; bearing inspection required",
    assignedTo: { id: "w1", name: "Marc J.", initials: "MJ" },
    dueDate: "2026-03-24",
  },
  {
    id: "wr-8910",
    status: "in_progress",
    priority: "high",
    asset: { id: "AST-CVB-12", label: "Conveyor Belt Motor" },
    location: "Line 2",
    category: "Mechanical",
    description: "Replace motor coupling per PM schedule",
    assignedTo: { id: "w2", name: "Sarah W.", initials: "SW" },
    dueDate: "2026-03-28",
  },
  {
    id: "wr-8894",
    status: "open",
    priority: "medium",
    asset: { id: "AST-LIFT-02", label: "Industrial Lift 2" },
    location: "Warehouse B",
    category: "Safety",
    description: "Annual inspection certification",
    assignedTo: null,
    dueDate: "2026-04-02",
  },
  {
    id: "wr-8840",
    status: "completed",
    priority: "low",
    asset: { id: "AST-ELP-01", label: "Main Power Panel" },
    location: "Electrical Room",
    category: "Electrical",
    description: "Thermal scan follow-up — cleared",
    assignedTo: { id: "w3", name: "David L.", initials: "DL" },
    dueDate: "2026-03-20",
  },
  {
    id: "wr-8822",
    status: "open",
    priority: "high",
    asset: { id: "AST-PMP-07", label: "Cooling Pump Skid 7" },
    location: "Chiller Yard",
    category: "Mechanical",
    description: "Seal leak reported on secondary pump",
    assignedTo: { id: "w4", name: "Elena R.", initials: "ER" },
    dueDate: "2026-03-29",
  },
  {
    id: "wr-8801",
    status: "in_progress",
    priority: "medium",
    asset: { id: "AST-FNX-03", label: "Forklift Charger 3" },
    location: "Shipping Dock",
    category: "Electrical",
    description: "Breaker trips under load — load study scheduled",
    assignedTo: { id: "w5", name: "James K.", initials: "JK" },
    dueDate: "2026-04-01",
  },
  {
    id: "wr-8777",
    status: "completed",
    priority: "medium",
    asset: { id: "AST-AHU-09", label: "AHU Unit 9" },
    location: "Office Wing",
    category: "HVAC",
    description: "Filter change and belt tension check",
    assignedTo: { id: "w2", name: "Sarah W.", initials: "SW" },
    dueDate: "2026-03-18",
  },
  {
    id: "wr-8755",
    status: "overdue",
    priority: "high",
    asset: { id: "AST-SPK-14", label: "Sprinkler Test Riser" },
    location: "Zone 3 (Garage)",
    category: "Life Safety",
    description: "Quarterly flow test documentation pending",
    assignedTo: { id: "w1", name: "Marc J.", initials: "MJ" },
    dueDate: "2026-03-22",
  },
];

export const WORK_REQUESTS_ANALYTICS = {
  total: 1240,
  avgCompletionDays: 2.4,
  volumeInsight: "Higher than normal request volume",
  volumeDelta: "+18% vs last month",
  criticalCount: 5,
  /** Catalog size for pagination copy when API is connected. */
  listTotal: 128,
};
